### ISSUE TITLE
Incorrect results and panic

### ISSUE THREAD

**Issue by osa1** [osa1/sg#5]
Repro steps:

- Clone https://github.com/ocaml/ocaml
- I'm trying with commit 2e065ea2d but I suspect any commit will do
- Run `sg --ocaml -k identifier 1`
- It will print incorrect matches, and then panic

Backtrace:

```
thread 'main' panicked at 'byte index 35 is out of bounds of `    ('a1, 'b1, 'c1, 'd1, 'e1, 'f1,`', src/main.rs:433:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::str::slice_error_fail
   3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/str/traits.rs:214:21
   4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/str/traits.rs:64:9
   5: sg::report_match
             at /home/omer/rust/sg/src/main.rs:433:19
   6: sg::walk_ast
             at /home/omer/rust/sg/src/main.rs:250:17
   7: sg::search_file
             at /home/omer/rust/sg/src/main.rs:198:5
   8: sg::walk_path
             at /home/omer/rust/sg/src/main.rs:174:17
   9: sg::walk_path
             at /home/omer/rust/sg/src/main.rs:171:13
  10: sg::run
             at /home/omer/rust/sg/src/main.rs:130:9
  11: sg::main
             at /home/omer/rust/sg/src/main.rs:50:15
  12: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Same thing happens if I search in Rust files in a large Rust repo (tried with rustc).

**Comment by osa1** [comment]
Fixed a few issues (code is a mess, will clean later (hopefully)). Need to implement CRLF handling before closing this.
